'use strict';

module.exports = {
    'things': ["Chinese giant salamander", "Great crested newt", "Sagalla caecilian", "Purple frog", "Lemur leaf frog", "Panamanian golden frog",
        "Common toad", "Barbour’s forest tree frog", "Axolotl", "Titicaca water frog", "Mallorcan midwife toad", "Smooth newt", "Western leopard toad",
        "African reed frog", "Dyeing poison frog", "Golden toad", "Natterjack toad", "Tomato frog", "Pool frog", "Japanese giant salamander",
        "Goliath frog", "Gardiner’s tree frog", "Cave salamander", "Arabian toad", "Corroboree frog", "African giant toad", "Golden frog",
        "Morelet’s tree frog", "Rabb's fringe-limbed treefrog", "Sunset frog", "Banana frog", "African wart frog", "Darwin’s frog",
        "Gold-striped salamander", "Lehmann’s poison frog", "North African fire salamander", "Water frog", "Southern gastric-brooding frog",
        "Granular poison frog", "Desert rain frog", "Acha Tugi long-fingered frog", "Cainarachi poison frog", "Gray wood frog", "Suriname toad",
        "Arum lily frog", "Flatwoods salamander", "Panamanian golden frog", "Green-eyed frog", "Torrent tree frog", "Table Mountain ghost frog",
        "Komodo dragon", "Arabian horned viper", "Black caiman", "Galapagos marine iguana", "Hawksbill turtle", "Parson’s chameleon",
        "Western diamond-backed rattlesnake", "Green iguana", "Loggerhead turtle", "Radiated tortoise", "Nile crocodile", "Short-horned chameleon",
        "Adder", "Aldabra giant tortoise", "Sand lizard", "American alligator", "Yellow sea snake", "Western swamp turtle", "Sail-fin lizard",
        "Grass snake", "Cuban crocodile", "Egyptian spiny-tailed lizard", "Alligator snapping turtle", "Galapagos giant tortoise",
        "Leatherback turtle", "Slow worm", "Tiger chameleon", "King cobra", "Spectacled caiman", "Aruba Island rattlesnake", "African rock python",
        "Gharial", "Madagascar tree boa", "Saltwater crocodile", "Fiji banded iguana", "Satanic leaf-tailed gecko", "Gila monster",
        "Olive ridley turtle", "Philippine crocodile", "Viviparous lizard", "Big-headed turtle", "African spurred tortoise", "Green anaconda",
        "Namaqua chameleon", "Afghan tortoise", "Beaked sea snake", "Orinoco crocodile", "Smooth snake", "African burrowing python",
        "Siamese crocodile", "King penguin", "African grey parrot", "Kakapo", "Andean flamingo", "Japanese crane", "Long-eared owl", "Ostrich",
        "Puffin", "Southern cassowary", "Bald eagle", "Kingfisher", "Emperor penguin", "Secretarybird", "Wilson’s bird-of-paradise",
        "California condor", "Blue-cheeked bee-eater", "Imperial eagle", "Albert's lyrebird", "Great spotted kiwi", "Green peafowl",
        "Philippine eagle", "Mallard", "Hyacinth macaw", "Galapagos penguin", "Burrowing owl", "Bee hummingbird", "Goldfinch", "Adélie penguin",
        "Osprey", "Blue bird-of-paradise", "Lappet-faced vulture", "American kestrel", "Robin", "Snowy owl", "Fire-maned bowerbird", "Blackbird",
        "Greater spotted eagle", "Large ground-finch", "Macaroni penguin", "Red kite", "Royal penguin", "Barn owl", "Cuckoo", "Emu",
        "Peregrine falcon", "Spix’s macaw", "Three-wattled bellbird", "Golden eagle", "Eurasian hobby", "Henderson petrel", "Tiger",
        "African elephant", "Blue whale", "Bornean orangutan", "Giant panda", "Brown bear", "Lion", "Orca", "Giraffe", "Polar bear",
        "Western gorilla", "Black rhinoceros", "African wild dog", "Bottlenose dolphin", "Snow leopard", "Hippopotamus", "Humpback whale",
        "Koala", "Jaguar", "Asian elephant", "Aardvark", "Red fox", "Moose", "Grey wolf", "Chimpanzee", "Cheetah", "Puma", "Ring-tailed lemur",
        "Giant armadillo", "Sperm whale", "Iberian lynx", "Aye-aye", "Brown hyaena", "Coyote", "Grevy’s zebra", "Pygmy three-toed sloth",
        "Red panda", "Wolverine", "Saola", "Red wolf", "Przewalski's horse", "Narwhal", "Clouded leopard", "Bonobo", "Black-footed ferret",
        "Caracal", "Black flying fox", "African wild ass", "Common vampire bat", "Fishing cat", "Black rhinoceros", "Hawksbill turtle",
        "Snow leopard", "Giant panda", "Great white shark", "Lion", "Blue whale", "Osprey", "Polar bear", "Coconut crab", "Humpback whale",
        "Emperor penguin", "African elephant", "Whale shark", "Red wolf", "Grass snake", "Chimpanzee", "Tiger", "Brown bear", "Green turtle",
        "Grey wolf", "Basking shark", "Red panda", "American alligator", "Cheetah", "Bald eagle", "Aye-aye", "Orca", "Asian elephant",
        "Royal penguin", "House spider", "Komodo dragon", "Bonobo", "Barbary falcon", "Shortfin mako", "Bottlenose dolphin", "African wild dog",
        "Puma", "Giant freshwater crayfish", "Iberian lynx", "Pygmy three-toed sloth", "African wild ass", "Adder", "Red fox", "Sperm whale",
        "Venus flytrap", "Jaguar", "Chinese giant salamander", "Alligator snapping turtle", "Barn owl", "Great white shark", "Coelacanth",
        "Leafy seadragon", "Queen triggerfish", "Southern bluefin tuna", "Whale shark", "Spotted handfish", "Pygmy seahorse", "Frilled shark",
        "Basking shark", "European eel", "Humphead parrotfish", "Giant manta ray", "Pike", "Great hammerhead", "Sunfish", "Atlantic salmon",
        "Bowmouth guitarfish", "Oceanic whitetip shark", "Smalltooth sawfish", "Yellowfin tuna", "Tiger shark", "Yangtze sturgeon", "Humphead wrasse",
        "Common seahorse", "Leopard shark", "River lamprey", "Swordfish", "Arapaima", "Ribbontailed stingray", "Red-bellied piranha", "Shortfin mako",
        "Beluga", "Anglerfish", "Megamouth shark", "Three-spined stickleback", "Spotted eagle ray", "Blacktip reef shark", "Albacore tuna", "Porbeagle",
        "Sharptooth lemon shark", "Rainbow parrotfish", "Green sawfish", "Pacific angel shark", "Big-belly seahorse", "Atlantic goliath grouper",
        "Salmon shark", "Common carp", "Thresher shark", "Bull shark", "Coconut crab", "Apollo butterfly", "Emperor scorpion", "Garden snail",
        "Monarch butterfly", "Large garden bumblebee", "Giant freshwater crayfish", "Common field grasshopper", "Dracula ant", "Honey bee",
        "Mexican rustleg tarantula", "Yabbie crayfish", "Seven-spot ladybird", "Mexican redknee tarantula", "Garden spider", "Common green darner",
        "Earthworm", "Mole cricket", "Queen Alexandra’s birdwing", "Stag beetle", "Death watch beetle", "Common wasp", "Green tiger beetle", "Adonis blue",
        "Medicinal leech", "Purse-web spider", "Trumpet-mouthed hunter snail", "Emperor moth", "Cinnabar moth", "Wallace’s golden birdwing butterfly",
        "House fly", "Oil beetle", "Ladybird spider", "Water scorpion", "Peppered moth", "Leaf-cutter ant", "Crab spider", "Black widow spider",
        "Common garden slug", "Horse-fly", "Six-spot burnet moth", "Zebra spider", "Peacock butterfly", "Common woodlouse", "Matrona", "Great pond snail",
        "Nursery-web spider", "Water spider", "Pill woodlouse", "House spider", "Giant clam", "Compass jellyfish", "Elkhorn coral", "Mushroom coral",
        "Purple sea urchin", "Horseshoe crab", "Flowerpot corals", "Common lobster", "Beadlet anemone", "Cauliflower corals", "Nautilus", "Staghorn coral",
        "Common octopus", "Edible sea urchin", "Native oyster", "Lace coral", "Sea lemon", "Velvet swimming crab", "Common cuttlefish", "Acorn barnacle",
        "Common starfish", "Fire corals", "Lugworm", "Sea slater", "North Pacific giant octopus", "Cuban cave shrimp", "Common jellyfish", "Black abalone",
        "Elegance coral", "Humboldt squid", "Razor shell", "Goose barnacle", "Closed brain coral", "Common shore crab", "Southern blue-ringed octopus",
        "Tall sea pen", "Jewel anemone", "Flat periwinkle", "Black corals", "Common limpet", "Ctenella coral", "Masked crab", "Pavona coral", "Sea-spider",
        "Finger coral", "Common whelk", "Curled octopus", "Common hermit crab", "Red coral", "Common cockle", "Venus flytrap", "Coco-de-mer",
        "Fanged pitcher plant", "Giant sequoia", "King protea", "St Helena olive", "Dragon tree", "Monkey puzzle", "Tennessee purple coneflower",
        "Flame tree", "Harlequin flower", "Rafflesia", "Lava cactus", "Sessile oak", "Titan arum", "Azobe", "Madagascar pitcher plant", "Greater cobra lily",
        "Ash", "Bluebell", "White lauan", "Black ebony", "Daisy", "Green pitcher plant", "Okoumé", "Red campion", "Horse chestnut", "Common dandelion",
        "Silver birch", "Fairy slipper orchid", "Bramble", "Mulanje cedar", "Red lauan", "Pedunculate oak", "Hawthorn", "Enteromorpha", "Common butterwort",
        "Brazil-nut tree", "Brazilian rosewood", "Jellyfish tree", "Lady’s slipper orchid", "Blackthorn", "Cow parsley", "Bladder wrack", "Sycamore",
        "Pennyroyal", "Bayahibe rose", "Common holly", "Bell heather", "Common chickweed", "Pink waxcap", "Coral tooth", "Beefsteak fungus", "Pig’s ear",
        "Boreal felt lichen", "Golden-gilled bolete", "Honey mushroom", "Lichen", "Nail fungus", "Death cap", "Fly agaric", "Mealy tooth", "Stinkhorn",
        "Weather earthstar", "Reindeer lichen", "Lichen", "Date waxcap", "Artist’s fungus", "Lichen", "Oak polypore", "Purple-red hygrophorus", "Lichen",
        "Devil's bolete", "Field mushroom", "Olive earthtongue", "Sandy stiltball", "Lichen", "King Alfred's cakes", "Violet crown-cup", "Lichen",
        "Ridged tooth", "Scrambled-egg lichen", "Grey tooth", "Lichen", "Orange-fruited elm-lichen", "Crater lichen", "Hat-thrower fungus", "Lichen",
        "Scaly tooth", "Zoned tooth", "Lichen", "Fused tooth", "Francis' lichen", "Lichen", "River jelly lichen", "Velvet tooth", "Lichen",
        "Scaly breck lichen", "Golden hair lichen", "Lichen"
    ]
};
